web:
  container_name: copo-web
  restart: always
  build: ./web/
  expose:
    - "8000"
  links:
    - mongo:mongo
    - postgres:postgres
    - redis:redis
  volumes:
    - ./web/src:/copo
    - ./media:/copo/media  
  env_file: .env
  command: bash -c "python manage.py makemigrations rest && python manage.py makemigrations chunked_upload && python manage.py makemigrations && python manage.py migrate && python /copo/setup/copo_social.py && /usr/local/bin/gunicorn web.wsgi:application -w 4 -t 1000 -b :8000"

nginx:
  container_name: copo-nginx
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - ./web/src/static:/www/static
  volumes_from:
    - web
  links:
    - web:web

mongo:
  container_name: copo-mongo
  image: mongo:latest
  ports:
    - "27017:27017"
  env_file: .env
  command: mongod
  volumes:
    - ./mongo/mongo-entrypoint/:/docker-entrypoint-initdb.d/
  #   - ./mongo/mongodata:/data/db

redis:
  container_name: copo-redis
  restart: always
  image: redis:latest
  ports:
    - "6379:6379"
  volumes:
    - redisdata:/data

postgres:
  container_name: copo-pg
  restart: always
  image: library/postgres
  ports:
    - "5432:5432"
  env_file: .env
  # volumes:
  #   - ./postgres/postgresdata:/var/lib/postgresql/data




